### ISSUE TITLE
post banner is not serving in https mode

### ISSUE THREAD

**Issue by phken91** [eexit/ghost-storage-cloudinary#107]
Hi, I am serving my ghost site in https mode,
But during create new post, upload an image in right hand side panel ( as know as post banner)
It's successful to upload, and show correctly in panel.

After publish the post, image wont show in post, in chrome developer tools, it show the error as below:
```
Mixed Content: The page at 'https://<mydomain>/' was loaded over HTTPS, but requested an insecure image 'http://<cloudinary url link>'. This request has been blocked; the content must be served over HTTPS.
```

Addon details:
Normal image upload in content is work fine.

Any idea on this? 
Thank you for help!

**Comment by eexit** [comment]
Hello,

Have you checked the https://github.com/eexit/ghost-storage-cloudinary#recommended-configuration?

Thanks.
