### ISSUE TITLE
Format option not working

### ISSUE THREAD

**Issue by yogeshbeniwal** [eexit/ghost-storage-cloudinary#119]
Adding both options for format and quality is resulting in wrong URL of https://res-2.cloudinary.com/NAME/image/upload/q_auto/v1/blog/2021/02/Testing.png.auto instead of  https://res-2.cloudinary.com/NAME/image/upload/q_auto,f_auto/v1/blog/2021/02/Testing.png

Below is the configuration used for Fetch section.

      "fetch": {
        "format": "auto",
        "quality": "auto",
        "secure": true,
        "cdn_subdomain": true
}

**Comment by joelgoodman** [comment]
@yogeshbeniwal I ran into this and did some digging. If you check the [Cloudinary Node docs](https://cloudinary.com/documentation/node_image_manipulation#converting_to_another_image_format), you want to use "fetch_format" as the key.
