### ISSUE TITLE
Not tested on Ghost version newer than 3

### ISSUE THREAD

**Issue by eexit** [eexit/ghost-storage-cloudinary#127]
Hello,

I appreciate your report and I am very pleased to see that this plugin is used. However, please be patient as I need more time to test it against the latest versions of Ghost.

Thanks a lot for your support :heart:

**Comment by frogonastring** [comment]
Hello! I'm being patient and I'm happy so please don't worry - but any progress on getting this tested with the latest version of Ghost?

**Comment by Czer0C** [comment]
I'm using Ghost 4.16.0 and it's working just fine.

**Comment by eexit** [comment]
🚀 https://github.com/eexit/ghost-storage-cloudinary/releases/tag/v2.2.0
