### ISSUE TITLE
Why is intallation instruction so specific about installing the package @2?

### ISSUE THREAD

**Issue by naz** [eexit/ghost-storage-cloudinary#130]
As seen in the [README's installation](https://github.com/eexit/ghost-storage-cloudinary/blob/ba3feef99d9074a6f63e69b7edbeb66d56b0009b/README.md?plain=1#L32) instructions it's recommended to install the package with `@2`. It's a bit unconventional comparing to most packages, so was wondering why the package should be installed this way?

**Comment by eexit** [comment]
Hi @naz,

It's because Ghost is releasing versions faster than I can keep up with and I try to have one version of this adapter per major Ghost version. Obviously, I'm failing at it so one day I should drop the `@x` versioning and drop compatibility toward older Ghost versions.

**Comment by eexit** [comment]
Closed by https://github.com/eexit/ghost-storage-cloudinary/commit/15ea891067427b5714c3935e267296a8b346254e.
