### ISSUE TITLE
Load image card error

### ISSUE THREAD

**Issue by bangden07** [eexit/ghost-storage-cloudinary#136]
Mixed Content: The page at 'https://gubuktekno.info/artikel/' was loaded over HTTPS, but requested an insecure image 'http://res-3.cloudinary.com/xxxx/image/upload/q_auto/v1/blog-images/ghost-cms.jpg'. This request has been blocked; the content must be served over HTTPS.

**Comment by eexit** [comment]
Hello,

Please read the Cloudinary's doc: https://cloudinary.com/documentation/image_transformations#secure_https_urls

Thanks.
