### ISSUE TITLE
chown: cannot dereference ‘/var/lib/ghost/content/adapters/storage/ghost-storage-cloudinary/node_modules/.bin/image-size’: No such file or directory

### ISSUE THREAD

**Issue by ANONIMNIQ** [eexit/ghost-storage-cloudinary#158]
I tried to install ghost-storage-cloudinary on my ghost blog in fly.io but after restarting my app I get this error:

`chown: cannot dereference ‘/var/lib/ghost/content/adapters/storage/ghost-storage-cloudinary/node_modules/.bin/image-size’: No such file or directory`

and my app crashed and needs restore,
how to fix this?

**Comment by eexit** [comment]
Hi, could you explain to me the steps you did for the installation?

Thanks!

**Comment by ANONIMNIQ** [comment]
I follow this guide but I guess I need to make something else for docker image:
https://smarative.com/blog/cloudinary-for-ghost-image-storage
