### ISSUE TITLE
Trying to serve images as webp

### ISSUE THREAD

**Issue by arbnorpuka** [eexit/ghost-storage-cloudinary#164]
Hello,

I tried to change the config.production.json, but adding the fetch format as .webp didn't work. Is there any workaround to this? 
Thanks in advance!

`"ghost-storage-cloudinary": {
      "useDatedFolder": false,
      "auth": {
        "cloud_name": "...",
        "api_key": "...",
        "api_secret": "..."
      },
      "upload": {
        "use_filename": true,
        "unique_filename": false,
        "overwrite": false,
        "folder": "blog-images",
        "tags": [
          "blog"
        ]
      },
      "fetch": {
        "quality": "auto",
        "secure": true,
        "cdn_subdomain": true,
        "format": "webp"
      },
      "plugins": {}
    }`

**Comment by eexit** [comment]
Hi @arbnorpuka,

Have you tried following this guide? https://cloudinary.com/documentation/node_image_manipulation#converting_to_another_image_format

Thanks!
