### ISSUE TITLE
Support Node 18

### ISSUE THREAD

**Issue by ceecko** [eexit/ghost-storage-cloudinary#167]
`ghost-storage-cloudinary` cannot be installed with Node.js v18 due to the following error:

```
error ghost-storage-cloudinary@2.2.5: The engine "node" is incompatible with this module. Expected version "^14.17.0 || ^16.13.0". Got "18.16.1"
```

Would it be possible to add support for Node.js v18?

**Comment by pankajpatel** [comment]
Would you happen to have any update on this change?

I can open an MR for this.

**Comment by tkisme** [comment]
#171
