### ISSUE TITLE
Docker Ghost 2.0 can't find `ghost-ignition`

### ISSUE THREAD

**Issue by BrnoPCmaniak** [eexit/ghost-storage-cloudinary#19]
I tried to follow the example of Dockerfile for the newest version and this message appears when I try to start it.

Not sure if your project isn't 2.0 compatible or where is the issue.

```
ghost                | module.js:550
ghost                |     throw err;
ghost                |     ^
ghost                | 
ghost                | Error: Cannot find module 'ghost-ignition'
ghost                |     at Function.Module._resolveFilename (module.js:548:15)
ghost                |     at Function.Module._load (module.js:475:25)
ghost                |     at Module.require (module.js:597:17)
ghost                |     at require (internal/module.js:11:18)
ghost                |     at Object.<anonymous> (/var/lib/ghost/versions/2.4.0/index.js:5:13)
ghost                |     at Module._compile (module.js:653:30)
ghost                |     at Object.Module._extensions..js (module.js:664:10)
ghost                |     at Module.load (module.js:566:32)
ghost                |     at tryModuleLoad (module.js:506:12)
ghost                |     at Function.Module._load (module.js:498:3)
```

**Comment by pascalandy** [comment]
Curious as well :)

**Comment by mmornati** [comment]
I can try to have a look to this version of the plugin. The one I stil' using on my side (where this one was forked) is still working https://github.com/mmornati/ghost-cloudinary-store
Maybe it is related to some of the new functions @eexit added to it?

**Comment by eexit** [comment]
Hello @BrnoPCmaniak,

I haven't tested the compatibility with version 2.x of Ghost. Will do as soon as I have the time for.
Sorry for the inconveniences.

**Comment by eexit** [comment]
This storage adapter is now compatible with Ghost 2.x. See the installation instructions in the README.
