### ISSUE TITLE
Not an issue, but just a query on compatibility with Ghost 3.0.

### ISSUE THREAD

**Issue by rolandng84** [eexit/ghost-storage-cloudinary#65]
Hi,
I've recently set up a blog with Ghost Version 3.1.1, just wondering if this plugin is compatible with this ghost blog version.

**Comment by eexit** [comment]
Hi Roland,

I haven't tested this on Ghost 3 branch yet. I will try to do it whenever I have a change 😉 

Thanks for your patience!

**Comment by eexit** [comment]
Hi @rolandng84,

I successfully tested this adapter for Ghost 3 and it's compatible. Feel free to install it on your side and provide feedback is something is not working as expected.

Thanks!
