### ISSUE TITLE
Node version error when en installing on docker

### ISSUE THREAD

**Issue by Edvin-Kjall** [eexit/ghost-storage-cloudinary#73]
ghost:3-alpine has NODE_VERSION=12.15.0 and your package only supports 8.10.0 || ^10.13.0
So can you bump the Node version or should I use ghost:2.38.0?

**Comment by eexit** [comment]
Thanks  @Edvin-Kjall for bringing this up. I added support for Node 12.x.

**Comment by eexit** [comment]
See https://github.com/eexit/ghost-storage-cloudinary/releases/tag/2.1.1.
