### ISSUE TITLE
Would be awesome  with webp support 

### ISSUE THREAD

**Issue by Edvin-Kjall** [eexit/ghost-storage-cloudinary#76]
You have the option to enable `fetch.quality = "auto"` would be awesome if you also could use
`fetch.format = "auto"` for the webp functionality.

**Comment by eexit** [comment]
Hey @Edvin-Kjall,

Feel free to add whatever option you wish in the [configuration](https://github.com/eexit/ghost-storage-cloudinary#configuration) section of your installation.

Thanks.
