### ISSUE TITLE
[Question] How do I check if this is working

### ISSUE THREAD

**Issue by ThePresence** [eexit/ghost-storage-cloudinary#98]
Hi,

I'm using digitalocean to host my ghost blog site. I've successfully installed this adapter, How do I configure this? As I checked configuration.json.dist file it is already configured and I've set cloude-name, api-key and secret key, It would be great if you could guide me as what to do next?

**Comment by eexit** [comment]
Hi @ThePresence,

Thanks for using this adapter. I'd suggest you take a quick look at the [README](https://github.com/eexit/ghost-storage-cloudinary#configuration).

Thanks.
